---
version: '2.4'

services:
  #---------------------------------------------------------------------------#
  # Schema Registry                                                           #
  #---------------------------------------------------------------------------#
  schema-registry-1:
    image: confluentinc/cp-schema-registry:5.1.0
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - "${KAFKA_CONNECT_SSL_TRUSTSTORE_LOCATION}:/kafka-truststore"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: ${ZOOKEEPER}
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-1
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: "/kafka-truststore"
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: ${KAFKA_CONNECT_SECURITY_PROTOCOL}
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 5000

  #---------------------------------------------------------------------------#
  # RADAR S3 connector                                                     #
  #---------------------------------------------------------------------------#
  radar-s3-connector:
    image: radarbase/radar-s3-connector:1.0.0
    restart: on-failure
    volumes:
      - ./sink-s3.properties:/etc/s3-connect/sink-s3.properties
      - "${KAFKA_CONNECT_SSL_TRUSTSTORE_LOCATION}:/kafka-truststore"
    depends_on:
      - schema-registry-1
    environment:
      CONNECT_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "default"
      CONNECT_CONFIG_STORAGE_TOPIC: "default.config"
      CONNECT_OFFSET_STORAGE_TOPIC: "default.offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "default.status"
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry-1:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry-1:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_OFFSET_STORAGE_FILE_FILENAME: "/tmp/connect2.offset"
      CONNECT_REST_ADVERTISED_HOST_NAME: "radar-s3-connector"
      CONNECT_ZOOKEEPER_CONNECT: zookeeper-1:2181
      CONNECTOR_PROPERTY_FILE_PREFIX: "sink-s3"
      CONNECT_SECURITY_PROTOCOL: ${KAFKA_CONNECT_SECURITY_PROTOCOL}
      CONNECT_SSL_TRUSTSTORE_LOCATION: "/kafka-truststore"
      CONNECT_PRODUCER_SECURITY_PROTOCOL: ${KAFKA_CONNECT_SECURITY_PROTOCOL}
      CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION: "/kafka-truststore"
      CONNECT_CONSUMER_SECURITY_PROTOCOL: ${KAFKA_CONNECT_SECURITY_PROTOCOL}
      CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION: "/kafka-truststore"
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx768m"
      KAFKA_BROKERS: 3
      CONNECT_LOG4J_LOGGERS: "org.reflections=ERROR"
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
