---
version: '2.4'

services:
  #---------------------------------------------------------------------------#
  # Schema Registry                                                           #
  #---------------------------------------------------------------------------#
  schema-registry-1:
    image: confluentinc/cp-schema-registry:5.1.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: ${ZOOKEEPER}
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-1
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: none
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 5000

  #---------------------------------------------------------------------------#
  # Fitbit Connectors                                                         #
  #---------------------------------------------------------------------------#

  fitbit-connect-instance:
    build:
      context: ../../
      dockerfile: docker/distributed-connect/Dockerfile
    image: radarbase/kafka-connect-rest-fitbit:latest
    depends_on:
      - schema-registry-1
    environment:
      CONNECT_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "rest-fitbit-connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "fitbit-connect-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "fitbit-connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "fitbit-connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry-1:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry-1:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: ${KAFKA_CONNECT_ADVERTISED_HOSTNAME}
      CONNECT_SECURITY_PROTOCOL: ${KAFKA_CONNECT_SECURITY_PROTOCOL}
      CONNECT_SSL_TRUSTSTORE_LOCATION: ${KAFKA_CONNECT_SSL_TRUSTSTORE_LOCATION}
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars,/usr/share/java/kafka-connect/plugins
    ports:
      - 8083:8083
